// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/auth/v1/auth.proto

package com.example.weatherdemoapplication.auth;

public final class AuthProtos {
    private AuthProtos() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface LoginRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:authv1.LoginRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string username = 1;</code>
         * @return The username.
         */
        java.lang.String getUsername();
        /**
         * <code>string username = 1;</code>
         * @return The bytes for username.
         */
        com.google.protobuf.ByteString
        getUsernameBytes();
    }
    /**
     * Protobuf type {@code authv1.LoginRequest}
     */
    public static final class LoginRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:authv1.LoginRequest)
            LoginRequestOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use LoginRequest.newBuilder() to construct.
        private LoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private LoginRequest() {
            username_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new LoginRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.example.weatherdemoapplication.auth.AuthProtos.internal_static_authv1_LoginRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.example.weatherdemoapplication.auth.AuthProtos.internal_static_authv1_LoginRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest.class, com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest.Builder.class);
        }

        public static final int USERNAME_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object username_ = "";
        /**
         * <code>string username = 1;</code>
         * @return The username.
         */
        @java.lang.Override
        public java.lang.String getUsername() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                username_ = s;
                return s;
            }
        }
        /**
         * <code>string username = 1;</code>
         * @return The bytes for username.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUsernameBytes() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                username_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest)) {
                return super.equals(obj);
            }
            com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest other = (com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest) obj;

            if (!getUsername()
                    .equals(other.getUsername())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + USERNAME_FIELD_NUMBER;
            hash = (53 * hash) + getUsername().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code authv1.LoginRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:authv1.LoginRequest)
                com.example.weatherdemoapplication.auth.AuthProtos.LoginRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.example.weatherdemoapplication.auth.AuthProtos.internal_static_authv1_LoginRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.example.weatherdemoapplication.auth.AuthProtos.internal_static_authv1_LoginRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest.class, com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest.Builder.class);
            }

            // Construct using com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                username_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.example.weatherdemoapplication.auth.AuthProtos.internal_static_authv1_LoginRequest_descriptor;
            }

            @java.lang.Override
            public com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest getDefaultInstanceForType() {
                return com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest.getDefaultInstance();
            }

            @java.lang.Override
            public com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest build() {
                com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest buildPartial() {
                com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest result = new com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest(this);
                if (bitField0_ != 0) { buildPartial0(result); }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.username_ = username_;
                }
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest) {
                    return mergeFrom((com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest other) {
                if (other == com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest.getDefaultInstance()) return this;
                if (!other.getUsername().isEmpty()) {
                    username_ = other.username_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                username_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }
            private int bitField0_;

            private java.lang.Object username_ = "";
            /**
             * <code>string username = 1;</code>
             * @return The username.
             */
            public java.lang.String getUsername() {
                java.lang.Object ref = username_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    username_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string username = 1;</code>
             * @return The bytes for username.
             */
            public com.google.protobuf.ByteString
            getUsernameBytes() {
                java.lang.Object ref = username_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    username_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string username = 1;</code>
             * @param value The username to set.
             * @return This builder for chaining.
             */
            public Builder setUsername(
                    java.lang.String value) {
                if (value == null) { throw new NullPointerException(); }
                username_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }
            /**
             * <code>string username = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearUsername() {
                username_ = getDefaultInstance().getUsername();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }
            /**
             * <code>string username = 1;</code>
             * @param value The bytes for username to set.
             * @return This builder for chaining.
             */
            public Builder setUsernameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) { throw new NullPointerException(); }
                checkByteStringIsUtf8(value);
                username_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:authv1.LoginRequest)
        }

        // @@protoc_insertion_point(class_scope:authv1.LoginRequest)
        private static final com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest();
        }

        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<LoginRequest>
                PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
            @java.lang.Override
            public LoginRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<LoginRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<LoginRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.example.weatherdemoapplication.auth.AuthProtos.LoginRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface LoginResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:authv1.LoginResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bool ok = 1;</code>
         * @return The ok.
         */
        boolean getOk();
    }
    /**
     * Protobuf type {@code authv1.LoginResponse}
     */
    public static final class LoginResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:authv1.LoginResponse)
            LoginResponseOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use LoginResponse.newBuilder() to construct.
        private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private LoginResponse() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new LoginResponse();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.example.weatherdemoapplication.auth.AuthProtos.internal_static_authv1_LoginResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.example.weatherdemoapplication.auth.AuthProtos.internal_static_authv1_LoginResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse.class, com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse.Builder.class);
        }

        public static final int OK_FIELD_NUMBER = 1;
        private boolean ok_ = false;
        /**
         * <code>bool ok = 1;</code>
         * @return The ok.
         */
        @java.lang.Override
        public boolean getOk() {
            return ok_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (ok_ != false) {
                output.writeBool(1, ok_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (ok_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, ok_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse)) {
                return super.equals(obj);
            }
            com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse other = (com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse) obj;

            if (getOk()
                    != other.getOk()) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + OK_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getOk());
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code authv1.LoginResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:authv1.LoginResponse)
                com.example.weatherdemoapplication.auth.AuthProtos.LoginResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.example.weatherdemoapplication.auth.AuthProtos.internal_static_authv1_LoginResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.example.weatherdemoapplication.auth.AuthProtos.internal_static_authv1_LoginResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse.class, com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse.Builder.class);
            }

            // Construct using com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                ok_ = false;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.example.weatherdemoapplication.auth.AuthProtos.internal_static_authv1_LoginResponse_descriptor;
            }

            @java.lang.Override
            public com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse getDefaultInstanceForType() {
                return com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse.getDefaultInstance();
            }

            @java.lang.Override
            public com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse build() {
                com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse buildPartial() {
                com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse result = new com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse(this);
                if (bitField0_ != 0) { buildPartial0(result); }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.ok_ = ok_;
                }
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse) {
                    return mergeFrom((com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse other) {
                if (other == com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse.getDefaultInstance()) return this;
                if (other.getOk() != false) {
                    setOk(other.getOk());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                ok_ = input.readBool();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }
            private int bitField0_;

            private boolean ok_ ;
            /**
             * <code>bool ok = 1;</code>
             * @return The ok.
             */
            @java.lang.Override
            public boolean getOk() {
                return ok_;
            }
            /**
             * <code>bool ok = 1;</code>
             * @param value The ok to set.
             * @return This builder for chaining.
             */
            public Builder setOk(boolean value) {

                ok_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }
            /**
             * <code>bool ok = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearOk() {
                bitField0_ = (bitField0_ & ~0x00000001);
                ok_ = false;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:authv1.LoginResponse)
        }

        // @@protoc_insertion_point(class_scope:authv1.LoginResponse)
        private static final com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse();
        }

        public static com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<LoginResponse>
                PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
            @java.lang.Override
            public LoginResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<LoginResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<LoginResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.example.weatherdemoapplication.auth.AuthProtos.LoginResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_authv1_LoginRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_authv1_LoginRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_authv1_LoginResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_authv1_LoginResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\030proto/auth/v1/auth.proto\022\006authv1\" \n\014Lo" +
                        "ginRequest\022\020\n\010username\030\001 \001(\t\"\033\n\rLoginRes" +
                        "ponse\022\n\n\002ok\030\001 \001(\0102E\n\013AuthService\0226\n\005Logi" +
                        "n\022\024.authv1.LoginRequest\032\025.authv1.LoginRe" +
                        "sponse\"\000BI\n\'com.example.weatherdemoappli" +
                        "cation.authB\nAuthProtosZ\022auth/proto/auth" +
                        "/v1b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_authv1_LoginRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_authv1_LoginRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_authv1_LoginRequest_descriptor,
                new java.lang.String[] { "Username", });
        internal_static_authv1_LoginResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_authv1_LoginResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_authv1_LoginResponse_descriptor,
                new java.lang.String[] { "Ok", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}